fix: cicd

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -1,40 +1,30 @@
-
 name: Bank Frontend Pipeline
-
 on:
   push:
     branches:
       - feature/*
       - main
-
   # pull_request:
   #   branches:
   #     - cicd
-
 jobs:
   Continues-Integration_build_and_push:
     runs-on: ubuntu-latest
-
     steps:
     - name: Checkout repository
-      uses: actions/checkout@v3
+      uses: actions/checkout@v4
     # with:
       #  repository: POD-13/Bank-Frontend
       #  ref: main
       
-
-
     - name: Log in to awscli
-      uses: aws-actions/configure-aws-credentials@v3
+      uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1
-
-
     - name: Build container image
       run: docker build -t bank-app-frontend:latest .
-
     - name: Log in to ECR with short-lived credentials
       run: |
         aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ vars.ECR_REPO }}
@@ -44,21 +34,18 @@ jobs:
     
     - name: Push image to ECR
       run: docker push ${{ vars.ECR_REPO }}/bank-frontend:${{ github.run_number }}
-
-
     - name: Clean up Docker image locally
+      if: always()
       run: |
         docker rmi bank-app-frontend:latest || true
         docker rmi ${{ vars.ECR_REPO }}/bank-frontend:${{ github.run_number }} || true
-
     - name: Clean up GitHub repo on runner
       run: rm -rf ./*
-
-
   
   Continues-Update_k8s_manifest:
     runs-on: ubuntu-latest
     needs: Continues-Integration_build_and_push
+    if: github.ref == 'refs/heads/main'
     steps:
     - name: Checkout repository.
       env:
@@ -70,11 +57,9 @@ jobs:
          cd Bank-Kubernetes-Manifest
          git config --global user.email "aitalsolomon983@gmail.com"
          git config --global user.name "Solomon Atalokhai"
-
          sed -i "s+${{ vars.ECR_REPO }}/bank-frontend:.*+${{ vars.ECR_REPO }}/bank-frontend:${{ github.run_number }}+g" ./bank-project/frontend.yaml
-
-         cat ./bank-project/frontend.yaml | grep -q "${{ vars.ECR_REPO }}/bank-frontend:${{ github.run_number }}"
-
+         grep -q "${{ vars.ECR_REPO }}/bank-frontend:${{ github.run_number }}" ./bank-project/frontend.yaml \
+           || { echo "Image tag update failed!"; exit 1; }
          git add bank-project/frontend.yaml
          git commit -m "Update frontend image to version ${{ github.run_number }}"
          git push origin main
